# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlsaver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locator',
            name='groupname',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
